# -*- coding: utf-8 -*-
"""intern_proj

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1-0h8UpkPGG2y_XxhgaAOEwjTqF6zS3
"""

import pickle
with open("/content/model .pkl", "rb") as f:
    clf= pickle.load(f)


import streamlit as st
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()

st.set_page_config(page_title="Iris Species Classifier", layout="centered")

st.title("🌸 Iris Species Prediction App")
st.write("Enter the flower measurements below to predict its species using a Decision Tree model.")

# Sliders for input
sepal_length = st.slider("Sepal Length (cm)", 4.0, 8.0, 5.1)
sepal_width = st.slider("Sepal Width (cm)", 2.0, 4.5, 3.5)
petal_length = st.slider("Petal Length (cm)", 1.0, 7.0, 1.4)
petal_width = st.slider("Petal Width (cm)", 0.1, 2.5, 0.2)

# Prediction
user_input = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
prediction = clf.predict(user_input)[0]
predicted_species = iris.target_names[prediction]

# Display result
st.success(f"🌼 The predicted species is: **{predicted_species.capitalize()}**")
